version: '3'

services:
  database:
    container_name: database
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=frontdesk
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=frontdesk
